require 'esearchy/SocialEngines/classmates'
require 'esearchy/SocialEngines/googleprofiles'
require 'esearchy/SocialEngines/linkedin'
require 'esearchy/SocialEngines/naymz'
require 'esearchy/SocialEngines/spoke'